import streamlit as st
import pandas as pd
from datetime import date
from guards import require_recorder
from db_core import fetch_all, exec_sql

@require_recorder
def show_recorder_management():
    # ==========================================================
    #  RECORDER PAGE 2: ADMIN MANAGEMENT
    # ==========================================================
    st.title("Admin Management")
    st.caption("Manage club data and system configuration")

    tabs = st.tabs([
        "👥 Manage Members",
        "🎯 Manage Rounds",
        "🏆 Competitions",
        "🥇 Championships",
    ])

    # ==========================================================
    # TAB 1: USER MANAGEMENT
    # ==========================================================
    with tabs[0]:
        st.subheader("👥 Manage Members")
        st.info("Add new club members. AV numbers are auto-generated by the database.")

        # Fetch all current members
        members = fetch_all("""
            SELECT cm.av_number AS AV_Number,
                   cm.full_name AS Name,
                   cm.birth_year AS Birth_Year,
                   g.gender_code AS Gender,
                   d.bow_type_code AS Division,
                   CASE WHEN cm.is_recorder THEN 'Recorder' ELSE 'Archer' END AS Role
            FROM club_member cm
            JOIN gender g ON g.id = cm.gender_id
            JOIN division d ON d.id = cm.division_id
            ORDER BY cm.full_name;
        """)

        if members:
            st.dataframe(pd.DataFrame(members), use_container_width=True)
        else:
            st.warning("No members found in the database.")

        genders = fetch_all("SELECT id, gender_code FROM gender ORDER BY gender_code;")
        divisions = fetch_all("SELECT id, bow_type_code FROM division WHERE is_active = 1 ORDER BY bow_type_code;")

        st.markdown("#### ➕ Add New Member")
        with st.form("add_member_form"):
            full_name = st.text_input("Full Name")
            current_year = date.today().year
            birth_year = st.number_input("Birth Year", 1900, current_year, 2000)
            gender_choice = st.selectbox(
                "Gender",
                options=[g["gender_code"] for g in genders] if genders else [],
            )
            division_choice = st.selectbox(
                "Division",
                options=[d["bow_type_code"] for d in divisions] if divisions else [],
                format_func=lambda code: {
                    "R": "Recurve",
                    "C": "Compound",
                    "RB": "Recurve Barebow",
                    "CB": "Compound Barebow",
                    "L": "Longbow",
                    "": "No Division",
                }.get(code, code),
            )
            is_recorder = st.checkbox("Is Recorder?")
            submitted = st.form_submit_button("Add Member")

            if submitted and full_name:
                exec_sql("""
                    INSERT INTO club_member (full_name, birth_year, gender_id, division_id, is_recorder)
                    VALUES (
                        :full_name,
                        :birth_year,
                        (SELECT id FROM gender WHERE gender_code = :gender),
                        (SELECT id FROM division WHERE bow_type_code = :division),
                        :is_recorder
                    );
                """, {
                    "full_name": full_name,
                    "birth_year": birth_year,
                    "gender": gender_choice,
                    "division": division_choice,
                    "is_recorder": is_recorder,
                })
                st.success(f"✅ Added new member: {full_name}")
                st.rerun()

    # ==========================================================
    # TAB 2: ROUND MANAGEMENT
    # ==========================================================
    with tabs[1]:
        st.subheader("🎯 Manage Rounds")
        st.info("Add new rounds and define their distance ranges.")

        rounds = fetch_all("SELECT id, round_name AS Name FROM round ORDER BY round_name;")
        if rounds:
            st.dataframe(pd.DataFrame(rounds), use_container_width=True)
        else:
            st.warning("No rounds found.")

        st.markdown("#### ➕ Add New Round")
        with st.form("add_round_form"):
            round_name = st.text_input("Round Name")
            submitted = st.form_submit_button("Create Round")
            if submitted and round_name:
                exec_sql("INSERT INTO round (round_name) VALUES (:name);", {"name": round_name})
                st.success(f"✅ Round '{round_name}' added.")
                st.rerun()

        st.markdown("#### ➕ Add Round Range")
        round_names = [r["Name"] for r in rounds] if rounds else []
        round_lookup = {r["Name"]: r["id"] for r in rounds} if rounds else {}
        with st.form("add_range_form"):
            selected_round = st.selectbox("Select Round", round_names)
            distance_m = st.selectbox("Distance (m)", [20, 30, 40, 50, 60, 70, 90])
            face_size = st.selectbox("Face Size (cm)", [80, 122])
            ends_per_range = st.selectbox("Ends per Range", [5, 6])
            submitted = st.form_submit_button("Add Range")
            if submitted and selected_round:
                exec_sql(
                    """
                    INSERT INTO round_range (round_id, distance_m, face_size, ends_per_range)
                    VALUES (:round_id, :distance_m, :face_size, :ends_per_range);
                    """,
                    {
                        "round_id": round_lookup[selected_round],
                        "distance_m": distance_m,
                        "face_size": face_size,
                        "ends_per_range": ends_per_range,
                    },
                )
                #st.success(f"✅ Range added to {selected_round}")
                st.rerun()

    # ==========================================================
    # TAB 3: COMPETITION SETUP
    # ==========================================================
    with tabs[2]:
        st.subheader("🏆 Manage Competitions")
        st.info("Create single-round competitions. All categories can participate.")

        comps = fetch_all("""
            SELECT c.id, c.name, c.start_date, c.end_date, 
                   r.round_name AS base_round, c.rules_note
            FROM competition c
            JOIN round r ON r.id = c.base_round_id
            ORDER BY c.start_date DESC;
        """)

        if comps:
            st.dataframe(pd.DataFrame(comps), use_container_width=True)
        else:
            st.warning("No competitions found.")

        round_options = fetch_all("SELECT id, round_name FROM round ORDER BY round_name;")

        st.markdown("#### ➕ Add New Competition")
        with st.form("add_comp_form"):
            name = st.text_input("Competition Name")
            start_date = st.date_input("Start Date")
            end_date = st.date_input("End Date")
            base_round_label = st.selectbox(
                "Base Round (required)",
                [r["round_name"] for r in round_options] if round_options else [],
            )
            rules_note = st.text_area("Rules / Notes")
            submitted = st.form_submit_button("Create Competition")
            
            if submitted and name and base_round_label:
                base_round_id = next(r["id"] for r in round_options if r["round_name"] == base_round_label)
                exec_sql(
                    """
                    INSERT INTO competition (name, start_date, end_date, base_round_id, rules_note)
                    VALUES (:name, :start, :end, :base_round_id, :rules);
                    """,
                    {
                        "name": name,
                        "start": start_date,
                        "end": end_date,
                        "base_round_id": base_round_id,
                        "rules": rules_note,
                    },
                )
                st.success(f"✅ Competition '{name}' created.")
                st.rerun()

    # ==========================================================
    # TAB 4: CHAMPIONSHIP CONFIGURATION
    # ==========================================================
    with tabs[3]:
        st.subheader("🥇 Manage Championships")
        st.info("Create multi-round championships with category-specific rankings.")

        # ==========================================================
        # SECTION A: LIST EXISTING CHAMPIONSHIPS
        # ==========================================================
        championships = fetch_all("""
            SELECT ch.id, ch.name, ch.start_date, ch.end_date,
                   CONCAT(ac.age_class_code, ' ', g.gender_code, ' ', d.bow_type_code) AS category,
                   COUNT(cr.id) AS num_rounds
            FROM championship ch
            JOIN category cat ON cat.id = ch.category_id
            JOIN age_class ac ON ac.id = cat.age_class_id
            JOIN gender g ON g.id = cat.gender_id
            JOIN division d ON d.id = cat.division_id
            LEFT JOIN championship_round cr ON cr.championship_id = ch.id
            GROUP BY ch.id, ch.name, ch.start_date, ch.end_date, category
            ORDER BY ch.start_date DESC;
        """)

        if championships:
            st.markdown("#### Current Championships")
            st.dataframe(pd.DataFrame(championships), use_container_width=True)
        else:
            st.warning("No championships configured yet.")

        # ==========================================================
        # SECTION B: ADD NEW CHAMPIONSHIP
        # ==========================================================
        categories = fetch_all("""
            SELECT cat.id, 
                   CONCAT(ac.age_class_code, ' - ', g.gender_code, ' - ', d.bow_type_code) AS category_name
            FROM category cat
            JOIN age_class ac ON ac.id = cat.age_class_id
            JOIN gender g ON g.id = cat.gender_id
            JOIN division d ON d.id = cat.division_id
            ORDER BY ac.age_class_code, g.gender_code, d.bow_type_code;
        """)

        st.markdown("#### ➕ Add New Championship")
        with st.form("add_championship_form"):
            champ_name = st.text_input("Championship Name")
            champ_start_date = st.date_input("Start Date", key="champ_start")
            champ_end_date = st.date_input("End Date", key="champ_end")
            category_label = st.selectbox(
                "Category (Age - Gender - Division)",
                options=[cat["category_name"] for cat in categories] if categories else [],
            )
            champ_rules_note = st.text_area("Rules / Notes", key="champ_rules")
            submitted_champ = st.form_submit_button("Create Championship")

            if submitted_champ and champ_name and category_label:
                category_id = next(cat["id"] for cat in categories if cat["category_name"] == category_label)
                exec_sql(
                    """
                    INSERT INTO championship (name, start_date, end_date, category_id, rules_note)
                    VALUES (:name, :start, :end, :category_id, :rules);
                    """,
                    {
                        "name": champ_name,
                        "start": champ_start_date,
                        "end": champ_end_date,
                        "category_id": category_id,
                        "rules": champ_rules_note,
                    },
                )
                st.success(f"✅ Championship '{champ_name}' created.")
                st.rerun()

        # ==========================================================
        # SECTION C: ADD ROUND TO CHAMPIONSHIP
        # ==========================================================
        round_choices = fetch_all("SELECT id, round_name FROM round ORDER BY round_name;")
        count_methods = {1: "Best 1", 2: "Best + 2nd"}

        st.markdown("#### ➕ Add Round to Championship")
        with st.form("add_champ_round_form"):
            champ_label = st.selectbox(
                "Select Championship",
                options=[f"{ch['name']} ({ch['start_date']})" for ch in championships] if championships else [],
            )
            round_label = st.selectbox(
                "Select Round",
                options=[r["round_name"] for r in round_choices] if round_choices else [],
            )
            method_label = st.selectbox(
                "Score Counting Method",
                options=list(count_methods.values()),
            )
            submitted_round = st.form_submit_button("Add Round")

            if submitted_round and championships and champ_label and round_label:
                champ_id = next(ch["id"] for ch in championships if f"{ch['name']} ({ch['start_date']})" == champ_label)
                round_id = next(r["id"] for r in round_choices if r["round_name"] == round_label)
                method_value = next(k for k, v in count_methods.items() if v == method_label)

                exec_sql(
                    """
                    INSERT INTO championship_round (championship_id, round_id, score_count_method)
                    VALUES (:championship_id, :round_id, :method)
                    ON DUPLICATE KEY UPDATE score_count_method = VALUES(score_count_method);
                    """,
                    {
                        "championship_id": champ_id,
                        "round_id": round_id,
                        "method": method_value,
                    },
                )
                # st.success("✅ Round added to championship.")
                st.rerun()
