import streamlit as st
import pandas as pd
from datetime import date
from guards import require_recorder
from db_core import fetch_all, exec_sql

@require_recorder
def show_recorder_management():
    # ==========================================================
    #  RECORDER PAGE 2: ADMIN MANAGEMENT
    # ==========================================================
    st.title("Admin Management")
    st.caption("Manage club data and system configuration")

    tabs = st.tabs([
        "👥 Manage Members",
        "🎯 Manage Rounds",
        "🏆 Competitions",
        "🥇 Championships",
    ])

    # ==========================================================
    # TAB 1: USER MANAGEMENT
    # ==========================================================
    with tabs[0]:
        st.subheader("👥 Manage Members")
        st.info("Add new club members. AV numbers are auto-generated by the database.")

        # Fetch all current members
        members = fetch_all("""
            SELECT cm.id,
                   cm.av_number AS AV_Number,
                   cm.full_name AS Name,
                   cm.birth_year AS Birth_Year,
                   g.gender_code AS Gender,
                   d.bow_type_code AS Division,
                   CASE WHEN cm.is_recorder THEN 'Recorder' ELSE 'Archer' END AS Role
            FROM club_member cm
            JOIN gender g ON g.id = cm.gender_id
            JOIN division d ON d.id = cm.division_id
            ORDER BY cm.full_name;
        """)

        if members:
            st.dataframe(pd.DataFrame(members), use_container_width=True)
        else:
            st.warning("No members found in the database.")

        genders = fetch_all("SELECT id, gender_code FROM gender ORDER BY gender_code;")
        divisions = fetch_all("SELECT id, bow_type_code FROM division WHERE is_active = 1 ORDER BY bow_type_code;")

        st.markdown("#### ➕ Add New Member")
        with st.form("add_member_form"):
            full_name = st.text_input("Full Name")
            current_year = date.today().year
            birth_year = st.number_input("Birth Year", 1900, current_year, 2000)
            gender_choice = st.selectbox(
                "Gender",
                options=[g["gender_code"] for g in genders] if genders else [],
            )
            division_choice = st.selectbox(
                "Division",
                options=[d["bow_type_code"] for d in divisions] if divisions else [],
                format_func=lambda code: {
                    "R": "Recurve",
                    "C": "Compound",
                    "RB": "Recurve Barebow",
                    "CB": "Compound Barebow",
                    "L": "Longbow",
                    "": "No Division",
                }.get(code, code),
            )
            is_recorder = st.checkbox("Is Recorder?")
            submitted = st.form_submit_button("Add Member")

            if submitted and full_name:
                exec_sql("""
                    INSERT INTO club_member (full_name, birth_year, gender_id, division_id, is_recorder)
                    VALUES (
                        :full_name,
                        :birth_year,
                        (SELECT id FROM gender WHERE gender_code = :gender),
                        (SELECT id FROM division WHERE bow_type_code = :division),
                        :is_recorder
                    );
                """, {
                    "full_name": full_name,
                    "birth_year": birth_year,
                    "gender": gender_choice,
                    "division": division_choice,
                    "is_recorder": is_recorder,
                })
                st.success(f"✅ Added new member: {full_name}")
                st.rerun()

    # ==========================================================
    # TAB 2: ROUND MANAGEMENT
    # ==========================================================
    with tabs[1]:
        st.subheader("🎯 Manage Rounds")
        st.info("Add new rounds and define their distance ranges.")

        rounds = fetch_all("SELECT id, round_name AS Name FROM round ORDER BY round_name;")
        if rounds:
            st.dataframe(pd.DataFrame(rounds), use_container_width=True)
        else:
            st.warning("No rounds found.")

        st.markdown("#### ➕ Add New Round")
        with st.form("add_round_form"):
            round_name = st.text_input("Round Name")
            submitted = st.form_submit_button("Create Round")
            if submitted and round_name:
                exec_sql("INSERT INTO round (round_name) VALUES (:name);", {"name": round_name})
                st.success(f"✅ Round '{round_name}' added.")
                st.rerun()

        st.markdown("#### ➕ Add Round Range")
        round_names = [r["Name"] for r in rounds] if rounds else []
        round_lookup = {r["Name"]: r["id"] for r in rounds} if rounds else {}
        with st.form("add_range_form"):
            selected_round = st.selectbox("Select Round", round_names)
            distance_m = st.number_input("Distance (m)", 10, 100)
            face_size = st.selectbox("Face Size (cm)", [80, 122])
            ends_per_range = st.selectbox("Ends per Range", [5, 6])
            submitted = st.form_submit_button("Add Range")
            if submitted and selected_round:
                exec_sql(
                    """
                    INSERT INTO round_range (round_id, distance_m, face_size, ends_per_range)
                    VALUES (:round_id, :distance_m, :face_size, :ends_per_range);
                    """,
                    {
                        "round_id": round_lookup[selected_round],
                        "distance_m": distance_m,
                        "face_size": face_size,
                        "ends_per_range": ends_per_range,
                    },
                )
                st.success(f"✅ Range added to {selected_round}")
                st.rerun()

    # ==========================================================
    # TAB 3: COMPETITION SETUP
    # ==========================================================
    with tabs[2]:
        st.subheader("🏆 Manage Competitions")
        st.info("Create competitions and assign their base round template.")

        comps = fetch_all("""
            SELECT c.id,
                   c.name AS Competition,
                   c.start_date AS Start,
                   c.end_date AS End,
                   r.round_name AS Base_Round,
                   c.rules_note AS Notes
            FROM competition c
            LEFT JOIN round r ON r.id = c.base_round_id
            ORDER BY c.start_date DESC;
        """)

        if comps:
            st.dataframe(pd.DataFrame(comps), use_container_width=True)
        else:
            st.warning("No competitions found.")

        round_options = fetch_all("SELECT id, round_name FROM round ORDER BY round_name;")

        st.markdown("#### ➕ Add New Competition")
        with st.form("add_comp_form"):
            name = st.text_input("Competition Name")
            start_date = st.date_input("Start Date")
            end_date = st.date_input("End Date")
            base_round_label = st.selectbox(
                "Base Round (optional)",
                ["None"] + [r["round_name"] for r in round_options],
            )
            base_round_id = (
                None
                if base_round_label == "None"
                else next(r["id"] for r in round_options if r["round_name"] == base_round_label)
            )
            rules_note = st.text_area("Rules / Notes")
            submitted = st.form_submit_button("Create Competition")
            if submitted and name:
                exec_sql(
                    """
                    INSERT INTO competition (name, start_date, end_date, base_round_id, rules_note)
                    VALUES (:name, :start, :end, :base_round_id, :rules);
                    """,
                    {
                        "name": name,
                        "start": start_date,
                        "end": end_date,
                        "base_round_id": base_round_id,
                        "rules": rules_note,
                    },
                )
                st.success(f"✅ Competition '{name}' created.")
                st.rerun()

    # ==========================================================
    # TAB 4: CHAMPIONSHIP CONFIGURATION
    # ==========================================================
    with tabs[3]:
        st.subheader("🥇 Manage Championships")
        st.info("Configure which rounds count towards championship ladders and how scores are aggregated.")

        competitions = fetch_all(
            """
            SELECT id, name, start_date
            FROM competition
            ORDER BY start_date DESC;
            """
        )
        championship_rules = fetch_all(
            """
            SELECT cr.id,
                   c.name AS Championship,
                   r.round_name AS Round,
                   CASE cr.score_count_method WHEN 1 THEN 'Best 1' ELSE 'Best + 2nd Best' END AS Method
            FROM championship_rule cr
            JOIN competition c ON c.id = cr.competition_id
            JOIN round r ON r.id = cr.round_id
            ORDER BY c.start_date DESC, r.round_name;
            """
        )

        if championship_rules:
            st.markdown("#### Current Championship Rules")
            st.dataframe(pd.DataFrame(championship_rules), use_container_width=True)
        else:
            st.warning("No championship rules configured yet.")

        round_choices = fetch_all("SELECT id, round_name FROM round ORDER BY round_name;")
        count_methods = {1: "Best 1", 2: "Best + 2nd Best"}

        st.markdown("#### ➕ Add Championship Rule")
        with st.form("add_champ_rule_form"):
            comp_label = st.selectbox(
                "Select Championship (competition)",
                options=[f"{c['name']} ({c['start_date']})" for c in competitions] if competitions else [],
            )
            round_label = st.selectbox(
                "Eligible Round",
                options=[r["round_name"] for r in round_choices],
            )
            method_label = st.selectbox(
                "Score Counting Method",
                options=list(count_methods.values()),
            )
            submitted = st.form_submit_button("Save Rule")

            if submitted and competitions:
                comp_id = next(c["id"] for c in competitions if f"{c['name']} ({c['start_date']})" == comp_label)
                round_id = next(r["id"] for r in round_choices if r["round_name"] == round_label)
                method_value = next(k for k, v in count_methods.items() if v == method_label)

                exec_sql(
                    """
                    INSERT INTO championship_rule (competition_id, round_id, score_count_method)
                    VALUES (:competition_id, :round_id, :method)
                    ON DUPLICATE KEY UPDATE score_count_method = VALUES(score_count_method);
                    """,
                    {
                        "competition_id": comp_id,
                        "round_id": round_id,
                        "method": method_value,
                    },
                )
                st.success("✅ Championship rule saved.")
                st.rerun()
